README.rst
docs/Makefile
docs/source/api_reference/index.rst
docs/source/conf.py
docs/source/index.rst
docs/source/tutorials/index.rst
setup.py
src/pseudopeople/__about__.py
src/pseudopeople/__init__.py

- *JIRA issue*: [MIC-3864](https://jira.ihme.washington.edu/browse/MIC-3864)
Replaces instances to all be pseudopeople.
N/A

Rename pseudo people to pseudopeople

---

.github/workflows/build.yml
docs/source/api_reference/index.rst
docs/source/glossary.rst
docs/source/index.rst
docs/source/installation.rst
docs/source/tutorials/getting_started.rst
docs/source/tutorials/index.rst
src/pseudopeople/noise.py

- *JIRA issue*: [MIC-3867](https://jira.ihme.washington.edu/browse/MIC-3867)
-Updates toctree
-Adds additional files needed (to be continued)
Doc builds pass.

Doc builds

---

docs/source/api_reference/index.rst
docs/source/api_reference/interface.rst
docs/source/concepts/configuration.rst
docs/source/concepts/forms.rst
docs/source/concepts/index.rst
docs/source/concepts/noise_functions.rst
docs/source/glossary.rst
docs/source/index.rst

- *JIRA issue*: [MIC-3867](https://jira.ihme.washington.edu/browse/MIC-3867)
-Added concepts directory with major concepts from Pseudopeople
-Added additional terms to glossary
Doc builds work without any errors.

Doc build 2

---

CHANGELOG.rst
src/pseudopeople/__about__.py

update changelog and version

---

src/pseudopeople/data/incorrect_select_options.csv
src/pseudopeople/noise_functions.py

- *JIRA issue*: [MIC-3937](https://jira.ihme.washington.edu/browse/MIC-3937)
-Changes is_w2 column to tax_form
-Changes data values from bool to "W2" and "1099"

Change tax_form column name and data values.

---

CHANGELOG.rst
src/pseudopeople/__about__.py

- *Category*: release
- *JIRA issue*: [MIC-3936](https://jira.ihme.washington.edu/browse/MIC-3936)
Increment version and update changelog
N/A

release candidate v0.2.0

---

src/pseudopeople/noise_functions.py

Fix row noise function signatures
Fix signature 
N/A

fix bug in row noise type signatures

---

CHANGELOG.rst
src/pseudopeople/__about__.py

release v0.3.2

---

src/pseudopeople/entity_types.py
src/pseudopeople/noise_entities.py
src/pseudopeople/utilities.py
tests/unit/test_column_noise.py
tests/unit/test_noise_form.py

- *JIRA issue*: [MIC-3982](https://jira.ihme.washington.edu/browse/MIC-3982)
-Adds noise level scaling function to ColumnNoiseTypes to adjust incorrect selection due to resampling with inclusion.
All tests pass successfully.

Adds noise level scaling function to ColumnNoiseType

---

src/pseudopeople/entity_types.py

- *JIRA issue*: [MIC-3902](https://jira.ihme.washington.edu/browse/MIC-3902)
-Adds logging message
Tests pass successfully.

Adds logging if no cells are noised

---

src/pseudopeople/interface.py
tests/integration/test_interface.py

- *Category*:  feature, refactor
- *JIRA issue*: [MIC-3962](https://jira.ihme.washington.edu/browse/MIC-3962)
- Adds date formatting for SSA event_date and dates of birth columns per documentation
- Refactors cognizable segments of the _generate_form helper into separate methods for readability
All pre-existing tests pass.

Add date formatting and refactor generate form helper

---

CHANGELOG.rst
src/pseudopeople/__about__.py

Release candidate v0.5.1

---

docs/source/datasets/index.rst
docs/source/index.rst

- *Category*: Documentation  
- *JIRA issue*: none 
Add initial description for dataset descriptions. 
Successfully built docs locally, visually checked

Add documentation for dataset descriptions 

---

src/pseudopeople/noise.py
src/pseudopeople/noise_entities.py
tests/unit/test_configuration.py
tests/unit/test_noise_form.py
tests/unit/test_row_noise.py

- *JIRA issue*: [MIC-3945](https://jira.ihme.washington.edu/browse/MIC-3945)
pytests pass

change 'omission' key to 'omit_rows'

---

src/pseudopeople/configuration/entities.py
src/pseudopeople/noise_entities.py
src/pseudopeople/noise_functions.py
tests/unit/test_column_noise.py

- *Category*: Refactor
- *JIRA issue*: [MIC-4004](https://jira.ihme.washington.edu/browse/MIC-4004)
-Update to typographic key name to replace original token.
Updates logic in function and tests to incorporate name change
All tests pass successfully

Typographic update

---

src/pseudopeople/__init__.py
src/pseudopeople/constants/metadata.py
src/pseudopeople/interface.py
tests/integration/test_interface.py
tests/unit/test_noise_form.py
tests/unit/test_row_noise.py

Fix name of ACS dataset - https://ihme.slack.com/archives/C02KUQ9LX32/p1681934664853799
N/A

fix name of ACS dataset

---

docs/source/api_reference/configuration.rst
docs/source/api_reference/configuration/index.rst
docs/source/api_reference/index.rst
docs/source/api_reference/interface.rst
docs/source/api_reference/noising/index.rst
src/pseudopeople/configuration/interface.py
src/pseudopeople/interface.py

- *JIRA issue*: [MIC-4011](https://jira.ihme.washington.edu/browse/MIC-4011)
docs build w/o warning

api reference context

---

docs/source/datasets/index.rst

Docs built locally and visually checked.

Add WIC dataset description to docs

---

docs/source/configuration/index.rst
docs/source/index.rst
docs/source/input_data/index.rst

Add page stubs for Input Data and Configuration

---

CHANGELOG.rst
src/pseudopeople/__about__.py

- *Category*: release
Updated changelog and version to 0.6.1
N/A

update version and changelog

---

docs/source/datasets/index.rst
docs/source/noise/index.rst

- Add the other API reference links to each dataset description following the format Zeb suggested in previous PR. 
- Add a description of W2 and 1099 forms.
- Add a description with a 'coming soon' announcement for 1040 form. 
n/a

Finish writing dataset descriptions documentation page 

---

CHANGELOG.rst
src/pseudopeople/__about__.py

update metadata for rc/v0.6.2

---

docs/source/datasets/index.rst
docs/source/index.rst

Document the simulation's timespan

---

docs/source/index.rst

Addressing landing page feedback from the docs session today. I didn't add anything about contacting us, since that seems like a larger conversation.

Change to beta, add next steps after quickstart

---

docs/source/index.rst
docs/source/noise/column_noise.rst

Revise from feedback

---

docs/source/noise/column_noise.rst

Document the "Use a fake name" noise type

---

docs/source/index.rst

This doesn't seem ideal, but it's probably better than nothing!
See the build below:

Add link to introduction/quickstart in sidebar

---

docs/source/glossary.rst
docs/source/index.rst
docs/source/noise/index.rst

Changes:
* Add "simulant" to glossary
* Sentence-case headings
* Reorder TOC

Make some minor presentation changes

---

docs/source/input_data/index.rst

Document pseudopeople input data

---

src/pseudopeople/constants/metadata.py
src/pseudopeople/noise_entities.py
src/pseudopeople/noise_functions.py
src/pseudopeople/schema_entities.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py

- *JIRA issue*: [MIC-3875](https://jira.ihme.washington.edu/browse/MIC-3875)
-Implementation for month day swap
-unit test for month day swap
Test framework passes.

Implement month day swap

---

docs/source/input_data/index.rst

- Use correct name for dataset generation functions
- Add some hyperlinks
- Bold the listed collections of input data.
This can be merged post-CODS.
Built locally

Improve Input Data page

---

.github/workflows/build.yml
README.rst
setup.py
src/pseudopeople/constants/metadata.py
src/pseudopeople/noise_entities.py
src/pseudopeople/noise_functions.py
src/pseudopeople/schema_entities.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py

- *Category*: other/misc
Cherry-picked commits from `develop-code` since that branch had its git history get a bit screwed up 
N/A

Merge changes stashed until after CODS

---

src/pseudopeople/schema_entities.py
tests/unit/test_column_noise.py

stop noising employer_id

---

setup.py
src/pseudopeople/utilities.py
tests/unit/test_column_noise.py
tests/unit/test_row_noise.py

###Updates pseudopeople to make compatible with new vivarium release.
- *JIRA issue*: [MIC-4058](https://jira.ihme.washington.edu/browse/MIC-4058)
-removes `random` used in older version of vivarium
-updates RandomnessStream instances to include now required argument IndexMap
Tests pass.

Unpin vivarium version

---

CHANGELOG.rst
setup.py
src/pseudopeople/__about__.py

- *JIRA issue*: [MIC-4074](https://jira.ihme.washington.edu/browse/MIC-4074)
Pin vivarium
Verified the package can be imported and can generate ACS (both of which failed before)

pip vivarium for the hotfix

---

docs/source/datasets/index.rst

- *JIRA issue*: [RT ticket](https://jira.ihme.washington.edu/browse/SSCI-1394) and [engineer ticket](https://jira.ihme.washington.edu/browse/MIC-4036) 
visually checked using make html

List household_id as an attribute in all datasets except SSA

---

.github/ISSUE_TEMPLATE/data_access_request.yml
.readthedocs.yaml
docs/source/datasets/index.rst
docs/source/noise/index.rst

Merge docs hotfixes to develop

---

docs/source/noise/column_noise.rst
docs/source/noise/index.rst

- *JIRA issue*: [SSCI-1404](https://jira.ihme.washington.edu/browse/SSCI-1404) (RT ticket) and [SSCI-1404](https://jira.ihme.washington.edu/browse/MIC-3875) (SE ticket)

Document swap month and day noise function 

---

docs/source/datasets/index.rst

- *JIRA issue*: [SSCI-1449](https://jira.ihme.washington.edu/browse/SSCI-1449)

Update 1040 form to remove employer and income columns

---

src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/schema_entities.py
src/pseudopeople/utilities.py

- *JIRA issue*: [MIC-4218](https://jira.ihme.washington.edu/browse/MIC-4218
-Formats 1040 for noising
-adds loader function to hold data utils functions for loading and formatting 1040
All tests pass and 1040 is formatted correctly with correct column names.

Mic 4218/format 1040

---

src/pseudopeople/schema_entities.py
src/pseudopeople/utilities.py

Adds metadata for 1040 dataset to schema entities.
- *JIRA issue*: [MIC-4208](https://jira.ihme.washington.edu/browse/MIC-4208)
-adds additional 1040 columns to schema entities 
-adds columns to 1040 dataset
All tests pass

Mic 4208/1040 metadata

---

src/pseudopeople/__init__.py
src/pseudopeople/configuration/generator.py
src/pseudopeople/constants/metadata.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/noise_functions.py
src/pseudopeople/schema_entities.py
src/pseudopeople/utilities.py

Implementation for 1040
- *JIRA issue*: [MIC-4210](https://jira.ihme.washington.edu/browse/MIC-4210)
-adds generate_tax_1040 function to interface.py
-updates metadata constants for additional 1040 columns for noising
-updates W2 date of birth config to be 0.0
All tests pass but test suites will be updated in the next ticket to incorporate the 1040.

Mic 4210/1040 implementation

---

.github/ISSUE_TEMPLATE/data_access_request.yml

Fixes #193; if anyone knows how to embed links in YAML, speak now!

Link to example access request

---

docs/source/noise/column_noise.rst
docs/source/noise/index.rst

- *JIRA issue*: [SSCI-1458](https://jira.ihme.washington.edu/browse/SSCI-1458)

Ensure all noise functions are verbs

---

docs/source/index.rst

- *JIRA issue*: [SSCI-1463](https://jira.ihme.washington.edu/browse/SSCI-1463)
checked visually with make html

Add link to pseudopeople website in readthedocs

---

docs/source/noise/index.rst

- *JIRA issue*: [SSCI-1447](https://jira.ihme.washington.edu/browse/SSCI-1447)
checked visually using make html

Add 1040 to noise table in pseudopeople docs

---

docs/source/datasets/index.rst
docs/source/noise/index.rst

- *Category*:  documentation 
- *JIRA issue*: [SSCI-1418](https://jira.ihme.washington.edu/browse/SSCI-1418)

Change income column to wages for W2 and 1099

---

.github/pull_request_template.md
docs/source/_static/style.css

- *JIRA issue*: [SSCI-1477](https://jira.ihme.washington.edu/browse/SSCI-1477)

Text wrap tables on Datasets page

---

src/pseudopeople/interface.py
src/pseudopeople/schema_entities.py

- *JIRA issue*: [MIC-4134](https://jira.ihme.washington.edu/browse/MIC-4134)
All tests pass

Mic-4134/remove extra columns

---

src/pseudopeople/constants/metadata.py
src/pseudopeople/interface.py
src/pseudopeople/utilities.py
tests/integration/test_interface.py
tests/unit/test_utils.py

- *Category*:  Bugfix
- *JIRA issue*: [MIC-4182](https://jira.ihme.washington.edu/browse/MIC-4182)
-adds function to cleanse int cols
All tests pass and int cols are all strings or nans.

Mic 4182/dtype mismatch bug

---

src/pseudopeople/interface.py
tests/integration/test_interface.py

- *JIRA issue*: [MIC-4061](https://jira.ihme.washington.edu/browse/MIC-4061
-changes how user filters are validated for year columns 
-raises value error if empty dataframe is loaded
-updates docstrings to match behavior
Manually tested and saw expected behavior. All tests pass.

Mic-4061/update-invalid-input-behavior

---

src/pseudopeople/configuration/interface.py
tests/unit/test_configuration.py

- *Category*: Refactor
- *JIRA issue*: [MIC-4464](https://jira.ihme.washington.edu/browse/MIC-4464)
-removes dataset_name arg from get_config
-updates related tests
All tests pass

Mic 4464/update get config

---

src/pseudopeople/schema_entities.py

- *JIRA issue*: [MIC-4490](https://jira.ihme.washington.edu/browse/MIC-4490)
-Fixes column order in W2 dataset
All tests pass

Update W2 column order

---

README.rst

Updating the README on GitHub to be more similar to our documentation.
None.

Align README with documentation

---

docs/source/index.rst
docs/source/tutorials/configuring_noise.rst

- *JIRA issue*: [SSCI-1473](https://jira.ihme.washington.edu/browse/SSCI-1473) and [SSCI-1474](https://jira.ihme.washington.edu/browse/SSCI-1474)
Included some commented-out code to help with rerunning this in the future (in the short term before we automate this further).
Fixed a bug in the quickstart where we did not calculate the number of true matches correctly. Hopefully this isn't too confusing.
Built locally.

Rerun code examples

---

src/pseudopeople/interface.py

Docstrings: Add NO_NOISE and other improvements

---

src/pseudopeople/interface.py

Edit docstring `year` descriptions

---

docs/source/datasets/index.rst

- *JIRA issue*: N/A, but here's the [Slack thread](https://ihme.slack.com/archives/C02KUQ9LX32/p1694046182455399)

Document survey date column in ACS & CPS

---

tests/unit/test_configuration.py

Adds tests for functionality introduced in #274.
Ran the tests.

Test possible_age_differences length check

---

src/pseudopeople/configuration/generator.py
src/pseudopeople/noise_functions.py

- *JIRA issue*: [MIC-4540](https://jira.ihme.washington.edu/browse/MIC-4540)
-changes all instances of yaml.full_load to yaml.safe_load
All tests pass

Mic-4540/yml safe load

---

CHANGELOG.rst

- *Category*: Release
-Updates changelog for release
All tests pass

Changelog for patch release 0.7.1

---

src/pseudopeople/__about__.py

- Updates package versio in __about__.py
All tests pass

Update package version

---

docs/source/noise/index.rst

- *JIRA issue*: [SSCI-1538](https://jira.ihme.washington.edu/browse/SSCI-1538)
Are there any other links or details that I should add here?

Add description of noise details section 

---

.github/workflows/deploy.yml

- *JIRA issue*: [MIC-4381](https://jira.ihme.washington.edu/browse/MIC-4381)
-Run tests on deployment

Mic-4381/Run tests on deploy

---

src/pseudopeople/__about__.py

v0.7.2 release

---

.github/workflows/deploy.yml

Fix typo in deploy yml

---

.github/workflows/build.yml
.github/workflows/deploy.yml

Mic-4384/change email sender name

---

.github/workflows/build.yml
.github/workflows/deploy.yml
src/pseudopeople/schema_entities.py
tests/unit/test_column_noise.py

- *JIRA issue*: [MIC-4173](https://jira.ihme.washington.edu/browse/MIC-4173)
-applies write wrong digits to age column
All tests pass

Mic 4173/miswrite numeric age

---

.gitignore
CHANGELOG.rst
docs/source/conf.py
pyproject.toml
setup.py
src/pseudopeople/__about__.py
src/pseudopeople/__init__.py

checked local dev install and got expected version

setuptools-scm

---

docs/source/noise/column_noise.rst

- *JIRA issue*: [SSCI-1515](https://jira.ihme.washington.edu/browse/SSCI-1515)

Fix NORC PVS link as a hotfix

---

src/pseudopeople/configuration/entities.py
src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/entity_types.py
src/pseudopeople/noise_entities.py
src/pseudopeople/noise_functions.py
src/pseudopeople/schema_entities.py
tests/integration/conftest.py
tests/unit/test_configuration.py
tests/unit/test_noise_form.py

- *JIRA issue*: [MIC-4741](https://jira.ihme.washington.edu/browse/MIC-4741)
-adds additional parameters as attribute to row noise types
-updates configuration to incorporate change
-updates and adds additional tests for new feature
All tests pass

Mic-4741/Implement additional parameters for row noise types

---

docs/source/datasets/index.rst

- *JIRA issue*: [SSCI-1541](https://jira.ihme.washington.edu/browse/SSCI-1541)

Add sentences about difference between W2 and 1040 forms

---

.github/workflows/deploy.yml
CHANGELOG.rst

- *Category*: 
CI
- *JIRA issue*: [MIC-4799](https://jira.ihme.washington.edu/browse/MIC-4799)

Update pypi publish with 2FA 

---

src/pseudopeople/constants/noise_type_metadata.py
src/pseudopeople/utilities.py
tests/conftest.py
tests/integration/test_interface.py
tests/unit/test_row_noise.py

- *Category*: Test
- *JIRA issue*: [MIC-4793](https://jira.ihme.washington.edu/browse/MIC-4793)
-moves helper functions to utilities
-adds FuzzyChecker to integration tests
-adds FuzzyChecker to additional unit tests
All tests pass

Mic-4793/fuzzy-checker-pt2

---

src/pseudopeople/interface.py
src/pseudopeople/noise_functions.py

- *JIRA issue*: [MIC-4833](https://jira.ihme.washington.edu/browse/MIC-4833)
-sorts census dataset by year and household id
All tests pass

Mic-4833/sort census

---

tests/unit/test_column_noise.py

- *JIRA issue*: [MIC-4837](https://jira.ihme.washington.edu/browse/MIC-4837)
-properly calculates the number of tokens that can be noised in our test data for make typos unit test. The test was passing before because the string lengths and number of tokens were close enough that we were still passing.
All tests pass

Mic 4837/make typos unit test update

---

setup.py

- *Category*: chore
Matches how we install them on CI:
https://github.com/ihmeuw/pseudopeople/blob/367661defef93bf12fd2977957fce52f03c625ca/.github/workflows/build.yml#L37
None.

Add lint tools to dev requirements

---

src/pseudopeople/noise_functions.py
src/pseudopeople/utilities.py
tests/unit/test_utils.py

- *Category*: Test
- *JIRA issue*: [MIC-4838](https://jira.ihme.washington.edu/browse/MIC-4838)
-adds unit tests for utility functions that were not previously being tested.
All tests pass

Mic-4838/unit test utility functions

---

docs/source/noise/index.rst
docs/source/noise/row_noise.rst

- *JIRA issue*: [SSCI-1666](https://jira.ihme.washington.edu/browse/SSCI-1666)

Hotfix: update order of duplication and omission noise functions

---

src/pseudopeople/__about__.py

Fix summary

---

docs/source/conf.py
docs/source/simulated_populations/index.rst
setup.py

Document Dask-distributed noising

---

CHANGELOG.rst
docs/source/conf.py
docs/source/simulated_populations/index.rst
setup.py
src/pseudopeople/constants/noise_type_metadata.py
src/pseudopeople/dtypes.py
src/pseudopeople/entity_types.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/noise.py
src/pseudopeople/noise_entities.py
src/pseudopeople/noise_functions.py
src/pseudopeople/output_dtype_getters.py
src/pseudopeople/schema_entities.py
src/pseudopeople/utilities.py
tests/integration/conftest.py
tests/integration/test_interface.py
tests/unit/test_column_noise.py
tests/unit/test_utils.py

- *Category*: 
Previously reviewed, except for CHANGELOG.

Release: dtypes fix, distributed noising

---

src/pseudopeople/noise_functions.py
tests/integration/conftest.py
tests/integration/test_dataset.py

- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-4875)
-updates omit_row and apply_do_not_respond noise functions to drop rows from missingness
-adds test to make sure missingness is in sync with current noised data
All tests pass

Mic-4875/Bugfix/missingness

---

.github/workflows/build.yml
setup.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/interface.py
src/pseudopeople/noise_functions.py
src/pseudopeople/utilities.py
tests/conftest.py
tests/unit/test_column_noise.py
tests/unit/test_row_noise.py
tests/unit/test_utils.py

- *JIRA issue*: [MIC-4881](https://jira.ihme.washington.edu/browse/MIC-4881)
-removes dependency on Vivarium
-removes all instances of RandomnessStream and replaces with numpy default rng
-All tests pass
-Environments build without install Vivarium

Mic 4881/remove randomness

---

.github/pull_request_template.md
pyproject.toml
src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/dataset.py
src/pseudopeople/noise_functions.py
tests/integration/test_dataset.py
tests/integration/test_interface.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py
tests/unit/test_row_noise.py

- *JIRA issue*: [MIC-5153](https://jira.ihme.washington.edu/browse/MIC-5153)

resolve mypy union-attr errors

---

pyproject.toml
src/pseudopeople/dataset.py
src/pseudopeople/noise_scaling.py
src/pseudopeople/utilities.py
tests/conftest.py

- *JIRA issue*: [MIC-5132](https://jira.ihme.washington.edu/browse/MIC-5132)
-fixes instances of no-any-return issues with mypy

Mic-5132/no-any-return

---

pyproject.toml
src/pseudopeople/configuration/interface.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/noise_scaling.py
src/pseudopeople/utilities.py
tests/conftest.py

- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-5155)
-fix return value mypy errors

Mic-5155/return-value

---

pyproject.toml
tests/unit/test_column_noise.py

- *Category*: 
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5188
I can't say I understand why this "fix" worked...

fix mypy error [dict-item]

---

.github/workflows/build.yml
pyproject.toml
setup.py
tests/integration/conftest.py

- *Category*: CI/infrastructure
- *JIRA issue*: [MIC-XYZ](https://jira.ihme.washington.edu/browse/MIC-5184)
- Removed unused fixtures that were triggering attr-defined 
- Added implicit reexport on the advice of this thread: https://github.com/python/mypy/issues/16596
- Reassignment to `min_version` and `max_version` with a new type was causing issues
- Updated build script to look for matching branches of `layered_config_tree`

fix mypy attr-defined errors

---

pyproject.toml
src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/interface.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/entity_types.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/noise_functions.py
tests/conftest.py
tests/integration/test_interface.py

- *Category*: typing
- *JIRA issue*: [MIC-5156](https://jira.ihme.washington.edu/browse/MIC-5156)
Resolve assignment errors.
Ran mypy.

assignment

---

pyproject.toml
src/pseudopeople/noise_functions.py
src/pseudopeople/utilities.py

- *Category*: 
feature
- *JIRA issue*: [MIC-5194](https://jira.ihme.washington.edu/browse/MIC-5194)
We got several errors for:
Name "np.Generator" is not defined  [name-defined]
Replaced with np.random.Generator

Mypy Errors: name-defined

---

pyproject.toml
src/pseudopeople/noise_entities.py

- *JIRA issue*: [MIC-5189](https://jira.ihme.washington.edu/browse/MIC-5189)

fix [has-type] error

---

pyproject.toml
src/pseudopeople/interface.py
src/pseudopeople/noise_functions.py
src/pseudopeople/utilities.py
tests/integration/conftest.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py
tests/unit/test_interface.py
tests/unit/test_noise_form.py

- *Category*: 
feature
- *JIRA issue*: [MIC-5195](https://jira.ihme.washington.edu/browse/MIC-5195)

Mypy Errors: No Untyped Call

---

src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/filter.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
tests/unit/test_configuration.py

- *Category*: refactor
- *JIRA issue*: [MIC-5196](https://jira.ihme.washington.edu/browse/MIC-5196)
Create DataFilter object to simplify access and typing of user provided filters 
All automated tests pass
*** REMINDER ***
CI WILL NOT RUN ANY TESTS MARKED AS SLOW (CURRENTLY INCLUDES INTEGRATION TESTS).
MANUALLY RUN SLOW TESTS LIKE `pytest --runslow` WITH EACH PR.
-->

create DataFilter object

---

docs/nitpick-exceptions
docs/source/conf.py
pyproject.toml
setup.py
src/pseudopeople/column_getters.py
src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/filter.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/utilities.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/test_dataset.py
tests/integration/test_interface.py
tests/integration/test_schema.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py
tests/unit/test_interface.py
tests/unit/test_noise_form.py
tests/unit/test_row_noise.py
tests/unit/test_utils.py

- *Category*: other/misc
- *JIRA issue*: [MIC-5196](https://jira.ihme.washington.edu/browse/MIC-5196)
Fixed no-untyped-def errors.
Apologies for the size...
Tests pass
*** REMINDER ***
CI WILL NOT RUN ANY TESTS MARKED AS SLOW (CURRENTLY INCLUDES INTEGRATION TESTS).
MANUALLY RUN SLOW TESTS LIKE `pytest --runslow` WITH EACH PR.
-->

fix no-untyped-def errors

---

docs/source/conf.py
pyproject.toml
setup.py
tests/conftest.py

- *Category*: 
-remove var-annotated mypy error

Mic-5186/mypy-var-annotated

---

.github/workflows/build.yml
CHANGELOG.rst

- *Category*: CI/infrastructure
- *JIRA issue*: [MIC-5258](https://jira.ihme.washington.edu/browse/MIC-5258)
Use a script to find matching dependency branches 
CI passes
*** REMINDER ***
CI WILL NOT RUN ANY TESTS MARKED AS SLOW (CURRENTLY INCLUDES INTEGRATION TESTS).
MANUALLY RUN SLOW TESTS LIKE `pytest --runslow` WITH EACH PR.
-->

use a script to find matching dependency branches

---

pyproject.toml

don't ignore list-item

---

.github/workflows/build.yml

-Add additional argument for workflow type to script

Add workflow type

---

docs/source/conf.py
pyproject.toml
setup.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/filter.py
src/pseudopeople/interface.py
src/pseudopeople/loader.py
src/pseudopeople/noise_functions.py
src/pseudopeople/output_dtype_getters.py
src/pseudopeople/utilities.py
tests/integration/test_interface.py

- *JIRA issue*: [MIC-5190](https://jira.ihme.washington.edu/browse/MIC-5190)
We should have done this error first b/c it opened up a bunch of typing
problems that were previously fixed.

Fix import-untyped errors

---

pyproject.toml
src/pseudopeople/configuration/entities.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/loader.py
src/pseudopeople/utilities.py
tests/conftest.py
tests/integration/test_interface.py
tests/unit/test_configuration.py

- *Category*: typing
- *JIRA issue*: [MIC-5193](https://jira.ihme.washington.edu/browse/MIC-5193)
Fix misc errors 
Build passes. 
*** REMINDER ***
CI WILL NOT RUN ANY TESTS MARKED AS SLOW (CURRENTLY INCLUDES INTEGRATION TESTS).
MANUALLY RUN SLOW TESTS LIKE `pytest --runslow` WITH EACH PR.
-->

Fix misc mypy errors

---

src/pseudopeople/configuration/noise_configuration.py
src/pseudopeople/dataset.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py
tests/unit/test_noise_form.py
tests/unit/test_row_noise.py

- *Category*: test refactor
- *JIRA issue*: [MIC-5305](https://jira.ihme.washington.edu/browse/MIC-5305)
Update unit tests.
Unit tests pass. Typing is failing because of integration tests which is updated in a separate PR.

row noising unit tests

---

src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/noise_configuration.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/noise_functions.py
src/pseudopeople/noise_level.py

- *Category*: refactor
- *JIRA issue*: [MIC-5306](https://jira.ihme.washington.edu/browse/MIC-5306)
Updates for column noising.
Created census dataset with default noising configuration.

column noising

---

src/pseudopeople/configuration/noise_configuration.py
tests/integration/test_dataset.py
tests/integration/test_interface.py
tests/unit/test_column_noise.py
tests/unit/test_noise_form.py
tests/unit/test_row_noise.py

- *Category*: tests
- *JIRA issue*: [MIC-5385](https://jira.ihme.washington.edu/browse/MIC-5385)
Update skipped tests.
All tests pass, including --runslow.

finish tests and typing

---

docs/source/conf.py
pyproject.toml
setup.py
src/pseudopeople/configuration/generator.py
src/pseudopeople/configuration/interface.py
src/pseudopeople/configuration/noise_configuration.py
src/pseudopeople/configuration/validator.py
src/pseudopeople/constants/data_values.py
src/pseudopeople/dataset.py
src/pseudopeople/entity_types.py
src/pseudopeople/interface.py
src/pseudopeople/noise_functions.py
src/pseudopeople/noise_level.py
src/pseudopeople/noise_scaling.py
src/pseudopeople/utilities.py
tests/conftest.py
tests/integration/conftest.py
tests/integration/test_interface.py
tests/unit/test_column_noise.py
tests/unit/test_configuration.py
tests/unit/test_noise_form.py
tests/unit/test_utils.py

- *Category*: typing
- *JIRA issue*: [MIC-5376](https://jira.ihme.washington.edu/browse/MIC-5376)
All typing errors resolved.
All tests (include slow tests) pass.

all typing errors

---

README.rst
docs/source/index.rst
setup.py
update_readme.py

- *JIRA issue*: [MIC-5669](https://jira.ihme.washington.edu/browse/MIC-5669)
This does a couple of things:
1. Tags the supported python versions in the README and reuses them in the docs
2. Tags the installation instructions in the README and reuses them in the docs
3. Automatically updates the README to match the python_versions.json.

Sbachmei/mic 5669/better handle supported python versions

---

Jenkinsfile

add full scale testing epic to Jenkins nightly builds

add full scale testing epic to Jenkins nightly builds

---

src/pseudopeople/schema_entities.py

remove phonetic error from MI column

remove phonetic error from MI column

---

docs/source/noise/index.rst

Remove phonetic error from middle initial column

---

tests/integration/test_interface.py
tests/unit/test_interface.py

- *Category*: 
- *JIRA issue*: [MIC-6020](https://jira.ihme.washington.edu/browse/MIC-6020)

Sbachmei/mic 6020/fix breaking test

---

.gitignore
setup.py
tests/integration/test_interface.py
tests/unit/test_interface.py

pin pyarrow and add vscode dir to gitignore

pin pyarrow and add vscode dir to gitignore

---

src/pseudopeople/interface.py
src/pseudopeople/utilities.py
tests/integration/release/test_release.py

- *JIRA issue*: [MIC-6045](https://jira.ihme.washington.edu/browse/MIC-6045)
Update census seed like we do with other datasets and add comments.

update census seed

---

Jenkinsfile

- *JIRA issue*: [MIC-5943](https://jira.ihme.washington.edu/browse/MIC-5943)
-skip mypy stage in Jenkins

Albrja/mic-5943/Add mypy to Jenkins

---

src/pseudopeople/interface.py
src/pseudopeople/noise_scaling.py
tests/integration/conftest.py
tests/integration/release/test_release.py

- *JIRA issue*: [MIC-5984](https://jira.ihme.washington.edu/browse/MIC-5984)
Set up two post-processing tests (test dtypes and test that ID cols were unnoised) to work with sharded data. 
Ran on all ACS, CPS, and WIC for RI.

post processing

---

pyproject.toml
tests/integration/release/test_release.py

- *JIRA issue*: [MIC-6139](https://jira.ihme.washington.edu/browse/MIC-6139)
Ran release test on ACS RI data with dask.

use LocalCluster in release tests

---

src/pseudopeople/noise_entities.py

add duplicate_with_guardian and remove duplicate_row

fix NoiseTypes docstring noising order
