ihmeuw/pseudopeople

src/pseudopeople/default_configuration.yaml, src/pseudopeople/entities.py, src/pseudopeople/utilities.py
- *JIRA issue*: [MIC-3860](https://jira.ihme.washington.edu/browse/MIC-3860)
- *Research reference*: https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#noise-functions
- Adds a `get_default_configuration` utility function that returns a ConfigTree object
- Adds a yaml for holding defaults. It is partially complete and will be updated with RT feedback and additional development.
Imported the utility, executed, and got an expected ConfigTree:
```
import pandas as pd
from pathlib import Path
from pseudopeople import utilities
utilities.get_default_configuration().to_dict()
```
gave output:
```
{'decennial_census': {'omission': 0.0145,
'duplication': 0.05,
'first_name': {'nickname': {'row_noise_level': …
```
=> Add get_default_configuration and defaults yaml

src/pseudopeople/entities.py, src/pseudopeople/entity_types.py, src/pseudopeople/noise.py, src/pseudopeople/noise_functions.py
Missing data noise function
- *Category*: Implementation
- *JIRA issue*: [MIC-3872](https://jira.ihme.washington.edu/browse/MIC-3872)
=> Missing data noise function

src/pseudopeople/interface.py, src/pseudopeople/utilities.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-3866](https://jira.ihme.washington.edu/browse/MIC-3866)
- Refactors get_default_configuration to get_configuration, optionally taking a YAML as argument
- Adds configuration parameter to existing census generation function
- Adds test for getting the default configuration and for getting a configuration of defaults overridden by supplied YAML.
- Adds a "user" layer alongside "base" for the ConfigTree noising configuration object
New tests work.
=> Support loading a yaml configuration file for overriding default configurations

src/pseudopeople/entities.py, src/pseudopeople/noise_functions.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-3862](https://jira.ihme.washington.edu/browse/MIC-3862)
This adds a few more tests. In addition:
- Rearranges existing __NoiseTypes to the correct order as well as adds missing ones
-  Adds missing noise_functions stubs
tests pass
=> add more tests

src/pseudopeople/default_configuration.yaml
- *JIRA issue*: [MIC-3925](https://jira.ihme.washington.edu/browse/MIC-3925)
-Updates default 
Ran generate_decennial_census successfully with required columns to experience noise have the configured percentage of noise applied to them.
=> Default config for initial release

tests/integration/conftest.py, tests/integration/test_interface.py
- *JIRA issue*: [MIC-3862](https://jira.ihme.washington.edu/browse/MIC-3862)
This is the final PR for MIC-3862 (pseudopeople testing framework); it adds an
integration test for the `generate_decennial_census` function.
NOTE: there are a few commented out assertions to be implemented as
we continue development. Do please review these commented out
portions even though they are not live to make sure we're not 
missing something.
NOTE: I'm using 100k data length because it seemed like a reasonable
compromise between time to build the data and allowable tolerance.
I'm happy to change if desired. Some basic profiling:
* 1 million rows: 90s runtime, max rtol = 0.02
* 100k rows: 12s runtime, max rtol = 0.07
* 10k rows: 5s runtime, max rtol = 0.15
pytests pass
=> add census integration test

src/pseudopeople/__init__.py, src/pseudopeople/default_configuration.yaml, src/pseudopeople/interface.py
- *JIRA issue*: [MIC-3869](https://jira.ihme.washington.edu/browse/MIC-3869)
- Adds `generate_w2` function to interface
- Adds relevant configuration to the defaults yaml
- Addition of a integration test is deferred pending merge of another PR
Running the `main` of `interface.py` and calling `generate_w2` resulted in noised data.
=> Add W2 generation interface 

src/pseudopeople/default_configuration.yaml
- *JIRA issue*: [MIC-3933](https://jira.ihme.washington.edu/browse/MIC-3933)
Simply changes is_w2 column to the new tax_form column in the default configuration. No existing tests are impacted.
Ran noising against data generated with modified PRL outputs. W2 data were noised as expected.
=> Change is_w2 to tax_form

src/pseudopeople/data/incorrect_select_options.csv, src/pseudopeople/default_configuration.yaml, src/pseudopeople/noise_functions.py, tests/unit/test_column_noise.py
- *JIRA issue*: [MIC-3907](https://jira.ihme.washington.edu/browse/MIC-3907)
-Adds numeric miswriting noise function
-Adds tests for numeric miswriting noise function
Test suites pass with no failures
=> Numeric miswriting

src/pseudopeople/__init__.py, src/pseudopeople/default_configuration.yaml, src/pseudopeople/interface.py, src/pseudopeople/schema_entities.py, src/pseudopeople/utilities.py, tests/integration/test_interface.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-3882](https://jira.ihme.washington.edu/browse/MIC-3882)
- Adds ACS, CPS, SSA, and WIC forms interfaces and default configuration
- Adds ability to pass in DataFrame as source data and pass in a dict as configuration
Manual testing, ran each noising function against each sample data. Noising succeeded with noising being seen in diffs between source and noising output.
=> Implement all non-1040 forms

src/pseudopeople/default_configuration.yaml, src/pseudopeople/noise_functions.py, src/pseudopeople/utilities.py, tests/integration/conftest.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py, tests/unit/test_noise_form.py
- *Category*: implementation
- *JIRA issue*: [MIC-3876](https://jira.ihme.washington.edu/browse/MIC-3876)
Note that I did NOT use the code Abie generated for age miswriting as it looped through everything whereas this takes a vectorized approach.
The current docs describe age miswrites as:
> To implement this, first select the rows for noise according to the row noise probability. For each selected row, the age will be adjusted. The adjustment value will be randomly selected from the configured list of possible perturbations, according to the configured probabilities of selection. If the probabilities of selection are a none/null value (which is the default), the choice is uniform among the list of possible perturbations.
> 
> For example, if the correct age is 28 and the possible …
=> implement age miswriting

tests/unit/test_column_noise.py
This moves the method that noises the pytest data three times
and ensures that (1) the same seed results in identical results and
(2) different seeds produce different results into its own
parameterized pytest.
pytests pass
=> refactor seed-check method into their own pytests

src/pseudopeople/noise_functions.py, src/pseudopeople/utilities.py, tests/unit/test_row_noise.py
- *JIRA issue*: [MIC-3870](https://jira.ihme.washington.edu/browse/MIC-3870)
-adds omit rows noising function and related test suites
All tests pass successfully.
=> Omission noise function

src/pseudopeople/interface.py, src/pseudopeople/schema_entities.py, tests/integration/test_interface.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-3909](https://jira.ihme.washington.edu/browse/MIC-3909)
- Adds year parameter to all form generation interfaces, defaulting to 2020
- For all forms but SSA, this will limit the noised output to that year
- For SSA forms, this will limit the noised output up to and including that year
- Adds tests for all this
- Adds a date_column attribute to FORMS, as these are the fields to filter by year on
Added tests work.
=> Add year argument to form generation functions

.github/CODEOWNERS
- *Category*: 
Update codeowners so that research can approve docs changes
Avoid hardcoding individuals' github accounts
Link to some information about codeowners: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
Will test once it's merged (can't do it until it's on develop)
=> update codeowners so that researchers can approve docs changes

src/pseudopeople/entity_types.py, src/pseudopeople/interface.py, tests/integration/test_interface.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-3960](https://jira.ihme.washington.edu/browse/MIC-3960)
This removes support of a user passing in a pd.DataFrame and requires
that the `source` arg be a path to the data root directory.
Added to the integration pytest that splits the sample data into
two smaller datasets and saves them to tmpdir, then uses tmpdir as
the input.
=> support only a path to data root directory

src/pseudopeople/noise_functions.py
-Changes missing data noise function to use np.nan instead of pd.NA to be consistent with PRL.
=> Switching to np.nan instead of pd.NA

src/pseudopeople/interface.py
- *JIRA issue*: [MIC-3962](https://jira.ihme.washington.edu/browse/MIC-3962)
Changes the ordering of the pre-noising formatting to avoid unnecessary type thrashing.
The tests pass.
=> Avoid unnecessary pd.to_datetime

src/pseudopeople/configuration/__init__.py, src/pseudopeople/configuration/entities.py, src/pseudopeople/configuration/generator.py, src/pseudopeople/configuration/validator.py, src/pseudopeople/entity_types.py, src/pseudopeople/noise_entities.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-3939](https://jira.ihme.washington.edu/browse/MIC-3939)
Refactored configuration.py into a module
Refactored get_configuration to split up code to generate the default config from the code to parse the user-provided config
Flipped the order of some arguments so we're consistently using default config as the first argument and user config second
Moved an age miswriting validation from the format function to the validation function
Restructured some configuration tests
Added automated tests
=> validate user configuration keys

CHANGELOG.rst, src/pseudopeople/configuration/entities.py, src/pseudopeople/configuration/generator.py, src/pseudopeople/entity_types.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-3945](https://jira.ihme.washington.edu/browse/MIC-3945)
This is the first of probably many PRs that are starting to conver the configuration
key names. 
https://uwnetid.sharepoint.com/:x:/r/sites/ihme_simulation_science_team/_layouts/15/Doc.aspx?sourcedoc=%7B52FC5569-29D6-40B1-B240-158C6AB7D043%7D&file=prl-configuration-item-names.xlsx&action=default&mobileredirect=true 
pytests pass
=> change 'row_noise_level' to 'probability'

setup.py, src/pseudopeople/interface.py, src/pseudopeople/noise.py, src/pseudopeople/utilities.py
- *JIRA issue*: [MIC-3987](https://jira.ihme.washington.edu/browse/MIC-3987)
- Adds tqdm to setup requirements
- Adds tqdm progress bar over the main noise_form loop
- Adds a logging message on opening a data file
- Sets default log level to INFO, configurable to DEBUG if verbose=True on an interface
Interactive output looks as expected:
```
>>> import pseudopeople as pp
>>> data = pp.generate_decennial_census()
2023-04-14 10:16:37.443 | INFO     | pseudopeople.interface:_generate_form:62 - Loading data from /Users/mkappel/git/pseudopeople/pseudopeople/src/pseudopeople/data/sample_forms/decennial_census_observer/decennial_census_observer.parquet.
Applying noise: 100%|███████████████████████████| 8/8 [00:00<00:00, 53.98type/s]
>>> data2 = …
```
=> Add logging and progress bar for generation of forms

src/pseudopeople/configuration/entities.py, src/pseudopeople/noise_entities.py, src/pseudopeople/noise_functions.py, tests/unit/test_column_noise.py
- *Category*: 
- *JIRA issue*: [MIC-4002](https://jira.ihme.washington.edu/browse/MIC-4002)
-Changes additional parameters to a list of probabilities for each of the 5 digits in a zipcode
-Changes key name to digit probabilities for the configuration 
All tests pass successfully.
=> Update zipcode miswriting

.github/CODEOWNERS
- *Category*: other/misc
These individuals aren't in ihmeuw/vivarium-research but should be able to approve docs changes
N/A
=> add individuals not in the ihmeuw org to codeowners

src/pseudopeople/entity_types.py, src/pseudopeople/noise.py, src/pseudopeople/noise_functions.py, tests/unit/test_row_noise.py
- *JIRA issue*: [MIC-4008](https://jira.ihme.washington.edu/browse/MIC-4008)
Adjust noise level for ACS and CPS omit rows
-Pass FORM object into row noise functions
All tests pass successfully
=> Scale ACS and CPS omission for oversampling

docs/source/datasets/index.rst
Docs built locally and checked visually by using 'make html'
=> Add attribute and column names to household survey docs

src/pseudopeople/configuration/generator.py, src/pseudopeople/configuration/validator.py, src/pseudopeople/constants/metadata.py, src/pseudopeople/noise_functions.py, src/pseudopeople/schema_entities.py, tests/conftest.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-4007](https://jira.ihme.washington.edu/browse/MIC-4007)
This PR adds to the already-existing age perturbation value checks. Specifically:
* zipcode digit probabilities: is it a list of exactly 5 floats between [0, 1]
* everything without a special validation function: is it a float between [0, 1] 
added pytests. all tests pass.
=> add user config value validation

src/pseudopeople/configuration/entities.py, src/pseudopeople/configuration/generator.py, src/pseudopeople/entity_types.py, src/pseudopeople/noise_entities.py, src/pseudopeople/noise_functions.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py, tests/unit/test_noise_form.py, tests/unit/test_row_noise.py
- *Category*: Refactor
- *JIRA issue*: [MIC-4022](https://jira.ihme.washington.edu/browse/MIC-4022)
- - *JIRA issue*: [MIC-4023](https://jira.ihme.washington.edu/browse/MIC-4023)
-Changes probability to cell probability for column noise types
-Changes probability to row probability for row noise types
All tests pass
=> Rename probability to cell and row probability

src/pseudopeople/interface.py
- Adds docstring text for getting all years from data by passing `year=None` to dataset generation functions
- Add None to the type annotation for years.
Tests pass and sphinx html docs looked good.
=> Add year=None text to generate_x docstrings and type annotations

src/pseudopeople/interface.py, src/pseudopeople/noise.py
Adds two static progress bars. top one for overall progress and bottom one
for specific file noising.
For sample data (ie only one dataset), only one progress bar.
we all did it on zoom and saw things
=> dual progress bars

docs/source/datasets/index.rst
- *JIRA issue*:none
This PR makes some updates to the Datasets page, based on conversations. Changes include: 
- separate ACS and CPS into their own sections
- remove overview table that was redundant
- change 'Simulant attributes' to 'Dataset columns'
checked using make html
=> Separate ACS and CPS dataset descriptions and remove redundant table

.github/workflows/build.yml, README.rst, setup.py
- *JIRA issue*: [MIC-3934](https://jira.ihme.washington.edu/browse/MIC-3934)
Removes support for Python 3.7
CI
=> Remove Python 3.7 support

docs/source/datasets/index.rst
@NathanielBlairStahn pointed out that this was incorrect the way I had tried to oversimplify it before. The timespans available in different datasets are not exactly the same and need to be noted as such in more places.
Also, thanks to @rmudambi's comment on Slack, I have added some explanation here of the data generated in the final, partial year of the simulation.
=> Revise explanation of simulation duration

docs/source/noise/column_noise.rst, docs/source/noise/index.rst
Changes:
* Reorder noise types
* Note that order matters (order the types are applied)
* Change names to match between table and details section
* Document borrowed SSN
* Add note about difference between write wrong digits and write wrong ZIP code digits
=> Reorder noise types

src/pseudopeople/configuration/generator.py, src/pseudopeople/constants/data_values.py, src/pseudopeople/noise_entities.py, src/pseudopeople/noise_functions.py, src/pseudopeople/schema_entities.py, tests/unit/test_configuration.py, tests/unit/test_noise_form.py, tests/unit/test_row_noise.py
_Note: a previous version of this PR aimed at a deleted develop branch is [here](https://github.com/ihmeuw/pseudopeople/pull/139)_
- *JIRA issue*: [MIC-3934](https://jira.ihme.washington.edu/browse/MIC-3934)
- Adds do_not_respond noising for census, ACS, and CPS
- Updates omission tests for the do_not_respond change
- Adds tests for do_not_respond proportionality and ports the oversampling testing previously done in the omission/omit_rows testing
- Adds test for incorrect dataset application of do_not_respond
- Adds test for omit_rows/do_not_respond mutual exclusivity 
- Adds test for correctness of census race/ethnicity, age, sex noise level adjustments
All tests work.
=> Implement targeted omission do_not_respond for census and surveys

src/pseudopeople/interface.py, tests/integration/test_interface.py
- *JIRA issue*: [MIC-4045](https://jira.ihme.washington.edu/browse/MIC-4045)
Instead of setting cell probability = 0, let's use their defaults but then increase
the column cell probabilities to 25% (which is enough to have noising
even for the sparsest columns, e.g. unit_number)
tests pass
=> include row-level noise in col-level integration tests

docs/source/input_data/index.rst
- *JIRA issue*: [MIC-4030](https://jira.ihme.washington.edu/browse/MIC-4030)
After discussion, we decided that the approach to checksums should be
one per zipped package and provided to the user via documentation. This PR
adds those hashes to the docs as well as a very brief description of what
they are an how to use them. 
na
=> add file hashes to doc

src/pseudopeople/configuration/generator.py, src/pseudopeople/configuration/validator.py, src/pseudopeople/entity_types.py, src/pseudopeople/noise_entities.py, src/pseudopeople/noise_functions.py, src/pseudopeople/noise_scaling.py, src/pseudopeople/schema_entities.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py, tests/unit/test_noise_form.py, tests/unit/test_row_noise.py
- *JIRA issue*: [MIC-4003](https://jira.ihme.washington.edu/browse/MIC-4003)
After re-naming all of the config keys, the noise entity class attributes did not
match. While not user facing, it was annoying/confusing. 
tests pass
=> align noise entity class attributes with names

.readthedocs.yaml
I've done this as a "docs hotfix" -- @ckkinuthia requested a PDF of the docs, so we can share it an a more easily comment-able form.
See RTD documentation on this: https://docs.readthedocs.io/en/latest/tutorial/index.html#enabling-pdf-and-epub-builds
No testing; I don't think there is a way to test this without it being in main?
=> Configure readthedocs to build a PDF

docs/source/api_reference/noising/index.rst, docs/source/configuration/index.rst
Adds some documentation of a special value that can be passed to dataset generation functions, to generate datasets with no (configurable) noise. (Configurable noise is all noise except "borrowed SSN.")
Built locally.
=> Document requesting no noise with a sentinel value

src/pseudopeople/configuration/entities.py, src/pseudopeople/configuration/generator.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-3968](https://jira.ihme.washington.edu/browse/MIC-3968)
-adds functionality for users to provide a value of "no_noise" as a user provided config to return an un-noised dataset.
-adds related test for functionality
=> Generate un-noised dataset

src/pseudopeople/__init__.py, src/pseudopeople/configuration/__init__.py, src/pseudopeople/configuration/entities.py, src/pseudopeople/configuration/generator.py, src/pseudopeople/configuration/interface.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-4203](https://jira.ihme.washington.edu/browse/MIC-4203)
-adds options for users to pass sentinel psp.NO_NOISE value to get_config
-fixes bug where strings and paths were not properly handled in get_config
All tests pass
=> Add docstring for no noise interface and fix bug

docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1376](https://jira.ihme.washington.edu/browse/SSCI-1376)
Re-doing this PR to merge to main instead of develop. 
'Choose the wrong option' (previously 'incorrect select' in concept model) was missing from the noise table in psp docs. Added for fields listed in concept model: state for any address; relationship to reference person; sex; race/ethnicity; type of tax form; and type of SSA event)
Edit: I also just noticed that 'head of household' is used in this table - I just updated it to 'reference person' to be consistent with the rest of documentation.
=> Update noise table to include choose the wrong option

docs/source/datasets/index.rst, docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1400](https://jira.ihme.washington.edu/browse/SSCI-1400)
Add "Noninstitutionalized GQ pop" and "Institutionalized GQ pop" to the values of "Relationship to reference person" in Census dataset table in pseudopeople docs. 
Sorry that this PR also includes the noise table update that I made yesterday - didn't realize it hadn't been merged yet but shouldn't cause any conflicts.
checked locally using make html
=> Add GQ values to 'relationship to reference person' in census dataset table - hot fix

tests/conftest.py
The pytest suite is taking 15-20 minutes to run which is far too long. 
This auto-marks all tests in the tests/integration/ directory as "slow"
and skips them. 
This means that we need to manually run `pytest --runslow` locally!
Tests are skipped. Went from 15 minutes to 2 on my laptop.
=> automatically tag all tests in integration/ as slow

src/pseudopeople/interface.py, src/pseudopeople/schema_entities.py, tests/integration/test_interface.py
- *Category*: Refactor
- *JIRA issue*: [MIC-4217](https://jira.ihme.washington.edu/browse/MIC-4217)
-Adds logic in _generate_dataset for special 1040 use case
Tested refactor by setting breakpoint and reaching 1040 special use case. All test suites pass.
=> Refactor to add logic for 1040 in interface

docs/source/datasets/index.rst, src/pseudopeople/configuration/generator.py, src/pseudopeople/constants/metadata.py, src/pseudopeople/entity_types.py, src/pseudopeople/interface.py, src/pseudopeople/noise.py, src/pseudopeople/noise_functions.py, src/pseudopeople/schema_entities.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py
- *JIRA issue*: none, but kind of a continuation of [MIC-3962](https://jira.ihme.washington.edu/browse/MIC-3962)
As documented in the concept model, the date formats should be:
- MMDDYYYY (no slashes) in WIC
- YYYYMMDD in SSA
- MM/DD/YYYY in all other datasets
This PR brings pseudopeople into alignment with this. Previously, WIC incorrectly used the default, and SSA incorrectly used the default in the date of birth column.
This turned out to be a much more involved change than I realized: previously, date format was incorrectly modeled as an attribute of the _column_ when it is really an attribute of the _dataset_. Please let me know if I've done this wrong.
Ran all tests, including with `--runslow`. Manually stepped through the swap month and day noise function to …
=> Match date formats to concept model

.github/pull_request_template.md
- *JIRA issue*: [MIC-4234](https://jira.ihme.washington.edu/browse/MIC-4234)
Integration tests are currently marked slow and are thus skipped by
CI. We need to remember to manually run them like `pytest --runslow`.
This just adds a reminder to the PR template to do that.
na
=> add reminder to run integration tests

README.rst, docs/source/index.rst
- *Category*: DOC
This adds a link to the pseudopeople mailing list signup page to the README and read-the-docs.
successfully built docs without warning, reviewed README.rst in GitHub and confirmed that link works.
=> DOC: add link to mailing list signup page

docs/source/datasets/index.rst
Previously our docs said all datasets had dates in YYYY-MM-DD. In fact, this is not the case.
You can see that this matches the code here:
https://github.com/ihmeuw/pseudopeople/blob/d1bf3bec5679c6db9deb6117af27dd07257185d3/src/pseudopeople/interface.py#L120-L127
Note that this code is **also** wrong, in that it does not match the concept model.
I will make another PR against `develop` to get everything (code and docs) in alignment with the concept model.
Built docs locally.
=> Doc hotfix: Correct date formats

docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1417](https://jira.ihme.washington.edu/browse/SSCI-1417)
Remove any mentions of 'wages' from the noise table in pseudopeople docs
Add 'write the wrong digits' to possible noise types for income
=> Hot fix: remove references to wages from noise table

docs/source/datasets/index.rst, docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1406](https://jira.ihme.washington.edu/browse/SSCI-1406), [SSCI-1414](https://jira.ihme.washington.edu/browse/SSCI-1414)
- Document adding "housing type" column to decennial census and ACS datasets
- Document adding "relationship to reference person" column to ACS dataset
- Edit noise table to include the new columns
- Specify desired category names for "housing type" and "relationship to reference person"
This is intended to be the official documentation for the engineers to implement these changes, as well as being the user-facing documentation.
The diff includes a bunch of whitespace deletions from my editor, so you may want to hide those.
=> DOC: Add columns to decennial census and ACS

.github/pull_request_template.md
We already have a reminder to run `pytest --runslow`. This just adds
a more visible checkbox.
=> add checkbox to pr template for slow tests

src/pseudopeople/configuration/generator.py, src/pseudopeople/configuration/interface.py, src/pseudopeople/configuration/validator.py, tests/integration/conftest.py, tests/integration/test_interface.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-4376](https://jira.ihme.washington.edu/browse/MIC-4376)
RT requested that when calling `psp.get_config()`, the user override
argument should be renamed from `user_config` to `overrides`.
integration tests pass
=> rename "user_config" arg to "overrides"

docs/source/noise/column_noise.rst, docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1457](https://jira.ihme.washington.edu/browse/SSCI-1457)
Edits the user docs to list the noise functions in the order in which the're applied in the code. Also makes a couple unrelated minor edits to one of the noise tables (see code comments below).
Technically, I put the noise types in an order that should be _equivalent_ to the order in which they're actually applied, but which I think will be more intuitive to a user reading the docs. I would like feedback on whether the order here looks good or whether we want to switch anything. If this ordering looks good, I'll edit the concept model accordingly and create an engineering ticket to update the code to match.
In particular, I have the following questions about what is the most logical …
=> DOC: Reorder noise functions in user docs

docs/source/datasets/index.rst
- *JIRA issue*: [SSCI-1507](https://jira.ihme.washington.edu/browse/SSCI-1507)
=> Hot fix: remove age from WIC dataset in pseudopeople docs

src/pseudopeople/exceptions.py
Nathaniel caught that we're inheriting from BaseException in our
custom exception dataclasses when we should be using Exception.
spot-tested in a try/except loop and custom error still got
raised but without the full stack trace
=> inherit from Exception instead of BaseException

src/pseudopeople/configuration/generator.py
There were two problems with this:
- It set a default for date of birth in the W2/1099 dataset; that column no longer appears in that dataset at all. Adding this had strange ripple effects, such as allowing the user to configure this (meaningless) setting.
- It was a duplicate key, overwriting the defaults defined above for the same dataset.
I ran the tests, but not the slow ones. I thought about adding an automated test that the rest of the default values are valid, but I'm not sure exactly where you would want to do this (at runtime or in a pytest) so I held off on that.
=> Set default noise values for W2/1099 correctly

src/pseudopeople/configuration/validator.py
Similar to #273, this was a place where the validator was throwing an unfriendly error message:
```pycon
>>> psp.generate_decennial_census(config={'decennial_census': {'column_noise': {'age': {'misreport_age': {'possible_age_differences': []}}}}})
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/mnt/share/homes/zmbc/src/pseudopeople/src/pseudopeople/interface.py", line 169, in generate_decennial_census
return _generate_dataset(DATASETS.census, source, seed, config, user_filters, verbose)
File "/mnt/share/homes/zmbc/src/pseudopeople/src/pseudopeople/interface.py", line 49, in _generate_dataset
configuration_tree = get_configuration(config)
File "/mnt/share/homes/zmbc/src/pseudopeople/src/pseudopeople/configuration/genera …
```
=> Check the length of possible_age_differences

src/pseudopeople/configuration/validator.py, src/pseudopeople/noise_scaling.py, tests/unit/test_configuration.py
- *JIRA issue*: none, I think?
Adding a warning analogous to what we do for nicknames when the user's configured value is not possible. Note that in this case it is impossible because of a limitation of pseudopeople, which could be fixed in the future, rather than an inherent limitation.
See Slack conversation at https://ihme.slack.com/archives/C02KUQ9LX32/p1693420562792379
Hoping to get @NathanielBlairStahn to review the language here. The warning looks like:
```pycon
>>> psp.configuration.get_configuration({'decennial_census': {'column_noise': {'state': {'choose_wrong_option': {'cell_probability': 0.99}}}}})
2023-08-30 21:19:45.827 | WARNING  | pseudopeople.configuration.validator:_validate_choose_wrong_option_probability:223 - Invalid 'cell_probability' provided …
```
=> Warn when choose_wrong_option target is impossible

src/pseudopeople/constants/data_values.py
The age intervals [in the documentation](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#id111) are listed as 0-4, 5-9, etc (inclusive, obviously, and after flooring age). These were copied exactly into pseudopeople, except that the intervals were only closed on the right. Some simulants therefore had NaN probabilities.
I think the 0-4, 5-9 notation is inherently confusing (because with that, it matters whether age is an integer or an exact decimal value), so I've opted for intervals closed on the left only here. Happy to change if people feel strongly.
Verified that after this change, there were no NaN probabilities.
=> Fix do_not_respond age intervals

src/pseudopeople/configuration/validator.py, tests/unit/test_configuration.py
- *Category*: bugfix/feature
I swear we had a Slack conversation and/or JIRA ticket about this, but I can't find it. There were two issues here:
- The warning message used the reciprocal when it shouldn't have (?)
- The warning message sounded far too authoritative/certain relative to what actually triggers it.
Hoping to get @NathanielBlairStahn to review this new wording. Note: I don't love the word "Invalid" still being present, but that would be more of a hassle to change.
```pycon
>>> psp.generate_decennial_census(config={'decennial_census': {'column_noise': {'first_name': {'use_nickname': {'cell_probability': 0.7}}}}})
2023-08-30 11:22:39.297 | pseudopeople.configuration.validator:_validate_nickname_probability:200 - Invalid 'cell_probability' provided for …
```
=> Improve nicknames maximum warning message

src/pseudopeople/interface.py, src/pseudopeople/noise.py, src/pseudopeople/noise_functions.py, src/pseudopeople/utilities.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py
- *JIRA issue*: [MIC-4276](https://jira.ihme.washington.edu/browse/MIC-4276)
Previously, we used the same seed in each shard. This lead to weird levels of noise correlation between shards, particularly when the shards were small (especially noticeable in survey datasets).
I verified that after this change, the ACS and CPS do_not_respond rates were well-calibrated in the RI data, and in the sample data (run across many overall seeds to get a good sample size).
=> Use different seed for each shard and noise type

docs/source/noise/column_noise.rst, docs/source/noise/index.rst
- *JIRA issue*: [SSCI-1401](https://jira.ihme.washington.edu/browse/SSCI-1401)
This noise type was implemented in [MIC-4041](https://jira.ihme.washington.edu/browse/MIC-4041) and is documented in the concept model [here](https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#noise-functions:~:text=digits%20of%20zip.-,Copy%20from%20within%20Household,-To%20allow%20for).
Built docs locally.
=> Document copy from household member noise

docs/source/configuration/index.rst, docs/source/noise/row_noise.rst
Our previous example no longer works, since we removed `omit_row` as a noise type from the Decennial.
Built locally.
=> Change configuration example

docs/source/api_reference/noising/index.rst, src/pseudopeople/interface.py
- *JIRA issue*: [SSCI-1523](https://jira.ihme.washington.edu/browse/SSCI-1523)
In the API Reference, changes all references to "pseudopeople input data" to "pseudopeople simulated population data," and changes "sample dataset" or "sample datasets" to "sample population". Also adds a link back to the Simulated populations page from the main Dataset Generation Functions page.
Built docs locally.
=> Change input data -> simulated population in docstrings

src/pseudopeople/interface.py
- *JIRA issue*: [SSCI-1520](https://jira.ihme.washington.edu/browse/SSCI-1520)
Wrap docstrings for `generate_x` functions at 72 chars, as per [PEP-8](https://peps.python.org/pep-0008/#maximum-line-length), and add whitespace for readability.
=> Docs: Clean up `generate_x` docstrings

src/pseudopeople/interface.py
- *JIRA issue*: [SSCI-1520](https://jira.ihme.washington.edu/browse/SSCI-1520)
Sequel to https://github.com/ihmeuw/pseudopeople/pull/301
Edits the description of the `state` parameter for all the `generate_x` docstrings to be more informative and match our language elsewhere.
=> Docstrings: Edit state parameter descriptions

src/pseudopeople/interface.py
- *JIRA issue*: [SSCI-1520](https://jira.ihme.washington.edu/browse/SSCI-1520)
Adds `ValueError` to the `:raises:` block of the `generate_x` docstrings, and removes it from the descriptions of the `year` and `state` parameters. Also changes wording for `ConfigurationError` and `DataSourceError` from "incorrect" to "invalid."
Built docs locally.
=> Docsrings: Add ValueError to :raises:

src/pseudopeople/utilities.py
- *Category*:  bugfix
git builds suddenly started failing for two pytests.
Turns out both tests us vectorized_choice and are breaking on the returned
np.take. Adding axis=0 seems to have fixed it, though I don't totally
understand why the default of None stopped working.
I did notice that python 3.8 built fine. When I installed 3.9 on my laptop
I see that numpy version is 1.26 which was just released two days ago -
so maybe there's a bug in there or a breaking change? It's just odd that
the tests this morning and then suddenly stopped building 20 minutes
later.
=> specify np.take axis

src/pseudopeople/interface.py, src/pseudopeople/utilities.py, tests/unit/test_interface.py
- *Category*:  test
There is probably a better way to do this than mocking the version extractor function
since that can cover bugs, but I did add a direct test on that so maybe it's fine.
Another approach could be to create multiple changelogs with different versions
to test against - happy to do that if that's better.
Note that these will all need to change with MIC-4546 but this at least gets the
validation wrapped in something that will break in the event that we don't get around
to that ticket and we try and update source data.
=> add data version tests

docs/source/simulated_populations/index.rst
- *Category*: Data/Documentation
- *JIRA issue*: [MIC-4556](https://jira.ihme.washington.edu/browse/MIC-4556)
-Adds new checksums
All tests pass
=> Mic-4556/v2.0.1_checksums

.github/workflows/build.yml
- *JIRA issue*: [MIC-4379](https://jira.ihme.washington.edu/browse/MIC-4379)
-Adds nightly build to run at 1AM
All tests pass
=> Mic-4379Add schedule build to CI

docs/source/datasets/index.rst
- *JIRA issue*: [SSCI-1539](https://jira.ihme.washington.edu/browse/SSCI-1539)
=> Remove references to noise functions on datasets page

docs/source/datasets/index.rst, docs/source/noise/column_noise.rst
- *JIRA issue*: [SSCI-1518](https://jira.ihme.washington.edu/browse/SSCI-1518)
The descriptions of missingness across the two pages are repetitive and somewhat vague, but not sure how to improve this. Lmk what you think!
=> Add missingness descriptions to datasets and noises pages

docs/source/noise/index.rst
- *Category*: docuentation 
- *JIRA issue*: [SSCI-1396](https://jira.ihme.washington.edu/browse/SSCI-1396)
Added this edit to the vivarium_research docs too ([in this PR](https://github.com/ihmeuw/vivarium_research/pull/1345))
=> Add write_wrong_digits to age column in noise table

docs/source/datasets/index.rst, docs/source/noise/column_noise.rst
- *JIRA issue*: [SSCI-1518](https://jira.ihme.washington.edu/browse/SSCI-1518)
=> Missingness descriptions hotfix

.github/workflows/build.yml, CHANGELOG.rst, setup.py
- *JIRA issue*: [MIC-4617](https://jira.ihme.washington.edu/browse/MIC-4617)
-drops support for python 3.8
=> Mic 4617/drop 3.8 support

.github/workflows/build.yml, tests/conftest.py, tests/unit/test_column_noise.py
- *Category*: Test
- *JIRA issue*: [MIC-4563](https://jira.ihme.washington.edu/browse/MIC-4563)
-adds --limit flag in confest test along with tests to use this flag on. Currently only test_noise_order
-adds a new test for write_wrong_digits which is an accuracy test for magnitude and marks old more robust test as slow
All tests pass. Limit flag works as intended.
=> Mic 4563/update for slow tests

CHANGELOG.rst, src/pseudopeople/noise_scaling.py
This is a minor bug, but unlike the other noise scaling, this one was not taking into account which simulants were even eligible to be noised on that column.
=> Scale copy-from noise with correct denominator

src/pseudopeople/interface.py
I was seeing crashes on the full USA data using the `epic/modin` branch. The root cause turned out to be the representation of some high-information columns such as simulant_id as pandas Categoricals in our Parquet outputs. This meant that the dtype of the column was holding a substantial amount of the data in that column, and Modin by default tries to materialize that dtype on a single node (see https://github.com/modin-project/modin/issues/5944#issuecomment-1758055361), which would OOM.
Note: I doubt we are getting any benefit by encoding as Categoricals, at least for these columns. This is a change we should consider making on the simulation/post-processing side.
=> Read parquet asynchronously with Modin

src/pseudopeople/loader.py, tests/integration/test_interface.py
- *JIRA issue*: None, workaround for [MIC-4620](https://jira.ihme.washington.edu/browse/MIC-4620)
Note that for the large data, this only affects the 1040, but for the sample data it affects all datasets. I don't know why this is.
After making this change, I can load and noise the USA 1040 data with Modin.
=> Drop index from simulated population data

CHANGELOG.rst, src/pseudopeople/entity_types.py, src/pseudopeople/interface.py, src/pseudopeople/noise.py, src/pseudopeople/noise_functions.py, src/pseudopeople/noise_scaling.py, src/pseudopeople/utilities.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_noise_form.py
- *Category*: performance
Speeds up the noising process by taking advantage of vectorization, avoiding unnecessary random number generation, and caching expensive information.
This is a large PR but I have broken it down into pretty atomic commits. You may want to review one at a time.
To get a pretty representative benchmark of pseudopeople performance, I noised the first two shards of each dataset in the full-USA data. On `main` this took about 15 minutes.
I profiled this benchmark with cProfile, and drilled down to what was taking the time in the noising process (within `noise_dataset`):
I then tried to address all the hotspots I saw in that benchmark. I didn't optimize all the noise functions, just the ones that seemed to be easily optimizable.
On this branch, the …
=> Optimize noise functions

CHANGELOG.rst, src/pseudopeople/__about__.py
- *Category*: release
PR #333 did not update the version number, causing the release to fail.
None.
=> Release 0.8.0

.github/workflows/build.yml
- *JIRA issue*: [MIC-4666](https://jira.ihme.washington.edu/browse/MIC-4666)
-updates format of command to trigger slow tests on schedule build
Tested new format with push event trigger.
=> Mic 4666/schedule build slow tests

CHANGELOG.rst, src/pseudopeople/interface.py
#333 introduced a bug when formatting dates that can have missingness. I did not consider this case because I thought dates were never missing, but their copy-from-household-member "shadow columns" can have missingness.
I ran this script to make the rare issue show up a lot:
```python
import pseudopeople as psp
data = psp.generate_social_security(
source="<USA data but with only one shard>",
config={
"social_security": {
"column_noise": {
"date_of_birth": {"copy_from_household_member": {"cell_probability": 1}}
}
}
}
)
print(data)
```
On `main` the output is:
```
simulant_id          ssn first_name middle_name   last_name date_of_birth     sex event_type event_date …
```
=> Fix bug formatting missing dates

docs/source/datasets/index.rst, docs/source/index.rst, docs/source/simulated_populations/index.rst
- *Category*: doc
Sam was confused that the default data all had zip code 00000, which he had been using for blocking in his pre-pseudopeople experiements.  I thought I'd make this clearer in the docs, in case it helped future users.
I could not remember how to build the docs locally, so we'll see if this passes CI as the test.
- ~~[ ] all tests pass (`pytest --runslow`)~~ --- Not necessary, since I just changed docs
=> DOC: add notes about Anytown, WA in default data

src/pseudopeople/interface.py
I didn't catch this before, because it only seems to affect the int columns, such as PO box.
No automated tests hit this code path, so I haven't run those.
Verified that I can now run:
```python
data = psp.generate_taxes_1040(
engine="modin",
)
data.to_parquet("./foo.parquet")
```
which was failing due to mixed dtypes before.
=> Coerce dtypes after noising with Modin

src/pseudopeople/configuration/generator.py, src/pseudopeople/noise_entities.py, src/pseudopeople/schema_entities.py, tests/integration/test_interface.py, tests/unit/test_configuration.py
- *JIRA issue*: [MIC-4566](https://jira.ihme.washington.edu/browse/MIC-4566)
-adds omit row to census and household surveys (ACS and CPS) -> docs: https://vivarium-research.readthedocs.io/en/latest/models/concept_models/vivarium_census_synthdata/concept_model.html#row-noise
Updated tests because do not respond and omit row are no logner mutually exclusive. All tests pass
=> Mic-4566/omit-row-update

src/pseudopeople/configuration/validator.py
- *JIRA issue*: [MIC-4565](https://jira.ihme.washington.edu/browse/MIC-4565)
-Fixes logic in user warning validation for noise proportions
-ALl tests pass
=> Don't return config in user warnings validation

docs/source/noise/row_noise.rst
- *JIRA issue*: [SSCI-1588](https://jira.ihme.washington.edu/browse/SSCI-1588)
=> Update docs for new default probability for omit_row

src/pseudopeople/interface.py, tests/unit/test_interface.py
- *JIRA issue*: [MIC-4712](https://jira.ihme.washington.edu/browse/MIC-4712)
-adds error message when directory does not contain subdirectory for simulated data for dataset to be noised
-adds related test
=> Mic 4712/invalid data path

src/pseudopeople/schema_entities.py
- *JIRA issue*: [MIC-4803](https://jira.ihme.washington.edu/browse/MIC-4803)
=> Remove use nickname from spouse last name column

docs/source/noise/index.rst, docs/source/noise/row_noise.rst
- *JIRA issue*: [SSCI-1585](https://jira.ihme.washington.edu/browse/SSCI-1585)
- Add & define guardian-based duplication to main Noise page in pseudopeople docs
- Describe guardian-based duplication and its parameters on Row Noise page (I'm not sure if I included too much or too little detail in this section, please lmk!) 
visually checked with make html
=> Update Psp docs for v1.0 release: guardian based duplication

tests/unit/test_column_noise.py, tests/unit/test_noise_form.py
- *Category*: Feature/tests
- *JIRA issue*: [MIC-4792](https://jira.ihme.washington.edu/browse/MIC-4792)
-replaces np.isclose for unit tests with fuzzy checker
-xfails OCR and phonetic errors tests because of known bug
All tests pass with expected failures.
=> Mic 4792/fuzzy checker unit tests

src/pseudopeople/noise_entities.py, tests/unit/test_column_noise.py, tests/unit/test_noise_form.py
- *JIRA issue*: [MIC-4809](https://jira.ihme.washington.edu/browse/MIC-4809)
-updates order of row noise types
All tests pass with new row noise order
=> Mic-4809/Update row noise order

src/pseudopeople/noise_entities.py, tests/unit/test_column_noise.py
- *JIRA issue*: [MIC-4807](https://jira.ihme.washington.edu/browse/MIC-4807)
-updates default configuration level of under 18 in households from 0.05 to 0.02
All tests pass
=> Mic-4807/Update noise level for under 18 in household

src/pseudopeople/noise_functions.py, tests/unit/test_column_noise.py
- *JIRA issue*: None, I think?
Fixes an issue with tracking which strings were "due" to be noised.
Based on #370 so that I can use the FuzzyChecker to add better tests that would have caught this bug.
Wrote new tests. Ran these tests without changing `_corrupt_tokens`; they failed. Updated the code and re-ran; tests passed.
=> Fix bug in _corrupt_tokens

src/pseudopeople/constants/noise_type_metadata.py, src/pseudopeople/interface.py, src/pseudopeople/noise_functions.py
- *JIRA issue*: [MIC-4832](https://jira.ihme.washington.edu/browse/MIC-4832)
-updates relationship to reference person column in guardian duplication noise function to match housing typefor copied rows
All tests pass
=> Mic-4832/guardian duplication relationships

src/pseudopeople/interface.py, tests/unit/test_column_noise.py
- *Category*: Test
- *JIRA issue*: [MIC-4794](https://jira.ihme.washington.edu/browse/MIC-4794)
-for our unit tests that test token noise, we want to test both at the token level and series level. We were doing that for all token noise types except for zipcode digits.
All tests pass
=> Mic-4794/fuzzy-checker-pt3

src/pseudopeople/noise_functions.py
- *JIRA issue*: [MIC-4862](https://jira.ihme.washington.edu/browse/MIC-4862)
-updates additional keys for randomness streams to ensure we are using randomness correctly. 
All tests pass
=> Mic 4862/randomness additional keys

src/pseudopeople/entity_types.py
- *JIRA issue*: [MIC-4866](https://jira.ihme.washington.edu/browse/MIC-4866)
-fixes check for empty column that allowed for an empty column to be noised
Noised a dataset with a config of noise level = 1 for leave blank. All tests pass.
=> Mic 4866/bugfix floating point error

src/pseudopeople/interface.py, tests/integration/test_schema.py
- *JIRA issue*: [MIC-4870](https://jira.ihme.washington.edu/browse/MIC-4870
-reverts census ordering due to runtime issues
All tests pass
=> Mic-4870/Revert census order

docs/source/noise/column_noise.rst
- *Category*: 
- *JIRA issue*: [SSCI-1784](https://jira.ihme.washington.edu/browse/SSCI-1784)
I also quickly reviewed other table titles but didn't see any other typos.
=> Hotfix: fix typo in make_typos parameter table title

docs/source/datasets/index.rst
- *Category*: 
- *JIRA issue*: [SSCI-1589](https://jira.ihme.washington.edu/browse/SSCI-1589)
=> Add brief explanation of why sample population has single city/state/zip 

src/pseudopeople/constants/noise_type_metadata.py, src/pseudopeople/entity_types.py, src/pseudopeople/interface.py, src/pseudopeople/schema_entities.py, src/pseudopeople/utilities.py, tests/integration/conftest.py, tests/integration/test_interface.py
Discovered in the course of working on #404 that there was some very strange dtype behavior going on: pseudopeople was returning columns with dtype "object" that contained integer objects. Our test was not catching this.
I've beefed up the test (got it actually failing on `main`), and fixed the issue with the integer columns to make them int dtypes.
=> Fix dtype bug in int columns

src/pseudopeople/interface.py, src/pseudopeople/noise.py, tests/integration/test_interface.py
The progress bars don't work when they aren't sequential. With a local Dask cluster, they would all overwrite each other; with a distributed Dask cluster, they were just never seen.
No progress bars appear.
=> Don't draw progress bars when using Dask

src/pseudopeople/dtypes.py, src/pseudopeople/entity_types.py, src/pseudopeople/interface.py, src/pseudopeople/noise_entities.py, src/pseudopeople/noise_functions.py, src/pseudopeople/output_dtype_getters.py, src/pseudopeople/schema_entities.py, src/pseudopeople/utilities.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_utils.py
I got some Pandas deprecation warnings after #405, and I think there were a few dtype quirks that were not being checked or handled correctly. The biggest one is that I'm pretty sure we've been noising the ".0" after the decimal point on integer columns this whole time, only for it to be lopped off at the end.
So instead, I made it more explicit what the dtype is after each noise function.
This actually makes a few of the Dask tests fail but I will correct those in a follow-up Dask PR.
=> Make dtype handling much more explicit

setup.py
*Technically* `distributed` isn't necessary if you use the most basic kind of Dask cluster (the kind that parallelizes via multiple threads in a single process) but that sort of Dask cluster isn't particularly helpful for pseudopeople.
None
=> Include distributed and dataframe extras with dask install

src/pseudopeople/interface.py
Long-term we may want to switch away from the global loguru logger, but for now making this consistent between Dask and non-Dask.
I ran the same thing that Nathaniel did when he noticed this problem (full USA ACS) and verified that the DEBUG logs were no longer displayed.
=> Configure logging on distributed Dask

src/pseudopeople/interface.py
When the user has Dask distributed installed, but is not currently running a cluster, this would fail with a ValueError.
=> Fix bug when there is no active Dask client

CHANGELOG.rst, setup.py
- *Category*: Build
- *JIRA issue*: [MIC-5121](https://jira.ihme.washington.edu/browse/MIC-5121)
-pin numpy below 2.0
=> Mic-5121/Pin numpy below 2.0

pyproject.toml
- *JIRA issue*: [MIC-5162](https://jira.ihme.washington.edu/browse/MIC-5162)
-remove call-arg mypy error
=> Mic-5162/call-arg

pyproject.toml, src/pseudopeople/entity_types.py, src/pseudopeople/noise_functions.py, src/pseudopeople/noise_level.py, tests/integration/test_interface.py, tests/unit/test_column_noise.py, tests/unit/test_row_noise.py
- *Category*: mypy
- *JIRA issue*: [MIC-5183](https://jira.ihme.washington.edu/browse/MIC-5183)
Fix mypy operator errors.
Ran mypy with operator error enabled and confirmed all remaining issues came from problems with checking containment in LayeredConfigTree objects.
=> mypy operator error

docs/nitpick-exceptions, src/pseudopeople/configuration/generator.py, src/pseudopeople/interface.py, tests/integration/conftest.py, tests/unit/test_column_noise.py, tests/unit/test_configuration.py
- *Category*: refactor
- *JIRA issue*: [MIC-5359](https://jira.ihme.washington.edu/browse/MIC-5359)
Remove references to NodeValue and NestedDict types from layered config tree.
mypy passes.
=> remove node value and nesteddict types

.github/workflows/build.yml, CHANGELOG.rst, README.rst, setup.py
- *JIRA issue*: [MIC-5575](https://jira.ihme.washington.edu/browse/MIC-5575)
-drop support for python 3.9
=> Albrja/mic-5575/drop support for python 3.9

tests/integration/conftest.py, tests/integration/test_interface.py
- *JIRA issue*: [MIC-5672](https://jira.ihme.washington.edu/browse/MIC-5672)
Remove one irrelevant test (test_generate_dataset_with_year). 
Replace one duplicative test (test_generate_dataset_from_multiple_shards).
Use FuzzyChecker to check if the amount of noising is the same whether using one or multiple shards.
Ran pytest with and without --runslow.
=> remove duplicate testing

.github/workflows/build.yml, .readthedocs.yaml, pyproject.toml, setup.py, tests/integration/release/test_release.py, tests/integration/release/test_runner.py, tests/utilities.py
- *JIRA issue*: [MIC-5503](https://jira.ihme.washington.edu/browse/MIC-5503)
Add with checks.
Added multiple assert statements that would fail using with check and verified that they all appeared in the output logs.
=> batch error logs

src/pseudopeople/noise_level.py, tests/integration/release/test_release.py, tests/integration/test_interface.py, tests/unit/test_configuration.py, tests/unit/test_row_noise.py, tests/utilities.py
- *JIRA issue*: [MIC-5516](https://jira.ihme.washington.edu/browse/MIC-5516)
Split out omit row and do not respond. 
Keep tests that proper noising types are defined on default configuration.
Ran tests. Census failed due to known bug but fuzzy checker caught the expected error. ACS and CPS passed when applying simple but temporary bugfix.
=> split and strengthen drop row tests

docs/source/noise/row_noise.rst
- *JIRA issue*: [SSCI-2150](https://jira.ihme.washington.edu/browse/SSCI-2150)
None
=> Note inexactness of do_not_respond row_probability

docs/nitpick-exceptions, docs/source/conf.py, setup.py, src/pseudopeople/dataset.py, src/pseudopeople/interface.py, tests/integration/test_interface.py, tests/unit/test_interface.py, tests/unit/test_utils.py, tests/utilities.py
- *Category*:  feature
- *JIRA issue*: https://jira.ihme.washington.edu/browse/MIC-5523
Dask by default uses a threaded scheduler which isn't helpful for these workloads.
This fixes it so that if first checks to see if a dask cluster is set up and, if so,
just uses that. If one isn't, it uses a `LocalCluster` with threads per node = 1.
=> change dask default client

src/pseudopeople/noise_level.py, tests/integration/release/test_release.py
- *JIRA issue*: [MIC-5893](https://jira.ihme.washington.edu/browse/MIC-5893)
Use a range instead of single value when fuzzy checking do not respond, expanding by 3% on both sides as described [here](https://github.com/ihmeuw/vivarium_research/pull/1600/files).
Ran test on acs, cps, and census sample data and acs and cps for full scale data.
=> update do not respond fuzzy checker

src/pseudopeople/dataset.py, src/pseudopeople/interface.py, src/pseudopeople/noise_functions.py, src/pseudopeople/noise_level.py, tests/integration/release/conftest.py, tests/integration/release/test_release.py, tests/unit/test_row_noise.py, tests/utilities.py
- *JIRA issue*: [MIC-5515](https://jira.ihme.washington.edu/browse/MIC-5515)
Add full scale test_dataset_missingness.
Typing.
Add default values to overload functions for generating data with dask.
Ran tests on acs, cps, and wic for RI and USA.
=> full scale test missingness

Jenkinsfile, tests/unit/test_interface.py
- *JIRA issue*: hotfix
When we run pytest --runslow, there are tests that run dask and set up a client which persists in the next tests. We were making an assumption that there is no dask client in test_set_up_dask_client_default. This PR shuts down a client if one already exists.
Ran pytest --runslow.
=> set up dask client test fix

setup.py
- *Category*: 
we pandas started pulling in the just-released pyarrow v20
as the default parquet engine. Interestingly, v20 is not marked
stable and there is no changelog or anything - we suspect it is a
mistake on apache's end. Regardless, we can't use it yet.
=> pin pyarrow <v20

src/pseudopeople/filter.py, src/pseudopeople/interface.py, src/pseudopeople/noise_functions.py, src/pseudopeople/schema_entities.py, tests/integration/release/test_release.py, tests/integration/release/utilities.py, tests/integration/test_interface.py, tests/unit/test_interface.py
- *JIRA issue*: [MIC-5982](https://jira.ihme.washington.edu/browse/MIC-5982)
Add tests for sequential row noising.
Read in data using load_standard_dataset and noise by looping through noise types, all shard-wise except RI with ACS, CPS, and WIC. 
Ran new tests with ACS, CPS, and WIC on USA and RI and SSA on RI.
=> sequential row noising

tests/integration/release/test_parallel_runs.py
- *JIRA issue*: [MIC-6094](https://jira.ihme.washington.edu/browse/MIC-6094)
Add 3 tests which
1. pass for all parameter combinations
2. fail for parameter combinations with census and pass otherwise
3. runs for 5 minutes with tax_1040 and run quickly otherwise (the tax_1040 jobs will get cancelled when we request sruns for 1 minute)
Testing
Ran pytest command with acs, census, and tax_1040 and checked that all tests passed, the second test failed, and the third test ran for longer than 1 minute, respectively.
=> write placeholder tests

src/pseudopeople/interface.py
- *JIRA issue*: [MIC-6113](https://jira.ihme.washington.edu/browse/MIC-6113)
use copy to avoid updating data in place when using dask
Ran pytest--runslow.
=> test_seed_behavior dask bugfix

tests/integration/release/test_release.py, tests/integration/release/utilities.py
- *JIRA issue*: [MIC-6178](https://jira.ihme.washington.edu/browse/MIC-6178)
Don't perform fuzzy checks if no simulants were eligible for noising in a shard.
=> don't fuzzy check empty shards in guardian duplication
